services:
    nginx:
      image: nginx:alpine
      ports:
        - "80:80"
      env_file:
        - .env
      volumes:
        - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./public:/var/www/html
      networks:
        - app-network

    php:
      build:
        context: .
        dockerfile: docker/dev/Dockerfile
      env_file:
        - .env
      volumes:
        - .:/var/www/html
        - ./docker/php/dev/php.ini:/usr/local/etc/php/conf.d/dev.ini
      networks:
        - app-network

    pgsql:
      image: postgres:14.15-alpine3.21
      restart: always
      environment:
        - POSTGRES_PASSWORD=password
      env_file:
        - .env
      volumes:
        - ./var/postgresql/data:/var/lib/postgresql/data
        - ./var/postgresql/logs:/var/log/postgresql:cached
      networks:
        - app-network

networks:
    app-network:
      driver: bridge